# Generated by Django 5.2.8 on 2026-01-11 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('EMP', 'Employee'), ('MAN', 'Manager')], default='EMP', max_length=3)),
                ('designation', models.CharField(choices=[('PA', 'PA'), ('ENG', 'Engineer'), ('CON', 'Consultant'), ('SB', 'Scientist B'), ('SC', 'Scientist C'), ('SD', 'Scientist D'), ('SE', 'Scientist E'), ('SF', 'Scientist F'), ('SG', 'Scientist G'), ('SH', 'Scientist H')], max_length=5)),
                ('color', models.CharField(default='#ec4899', max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
