# Generated by Django 5.2.8 on 2026-01-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(choices=[('PA', 'PA'), ('ENG', 'Engineer'), ('CON', 'Consultant'), ('SB', 'Scientist B'), ('SC', 'Scientist C'), ('SD', 'Scientist D'), ('SE', 'Scientist E'), ('SF', 'Scientist F'), ('SG', 'Scientist G'), ('SH', 'Scientist H')], max_length=50),
        ),
    ]
