# Generated by Django 5.2.8 on 2026-01-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='total_days',
        ),
        migrations.AddField(
            model_name='leave',
            name='decision_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='reason',
            field=models.TextField(default='No reason provided'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'Casual Leave'), ('RH', 'Restricted Holiday')], max_length=5),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
