# Generated by Django 5.2.8 on 2026-01-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_remove_leave_total_days_leave_decision_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='UPCOMING', max_length=20),
        ),
    ]
