# Generated by Django 5.2.8 on 2026-01-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_meeting_created_by_alter_meeting_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='status',
        ),
        migrations.AddField(
            model_name='meeting',
            name='repeat',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
