# Generated by Django 5.2.8 on 2026-01-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_remove_meeting_description_remove_meeting_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
