# Generated by Django 5.2.8 on 2026-01-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_meeting_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
    ]
