# Generated by Django 5.2.8 on 2026-01-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0007_meeting_status_alter_meeting_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('last_number', models.IntegerField(default=0)),
            ],
        ),
    ]
