# Generated by Django 5.2.8 on 2026-01-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0008_filenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.TextField(),
        ),
    ]
