# Generated by Django 5.2.8 on 2026-01-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0009_alter_leave_leave_type_alter_leave_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveFileCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('last_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='FileNumber',
        ),
    ]
